### PR TITLE
Add compile instructions for Alpine

### PR DESCRIPTION
**Pull request by oscar-b**
Original Dockerfile from @Rishka in #70, slightly modified to Curl release file instead of clone with Git

### CODE REVIEW

**Comment by joshourisman** [comment]
Not sure if it's really in scope, but this is a perfect application of multi stage builds in newer Docker versions, the following Dockerfile results in a container with working sentry-cli, but only a 16.8 MB image size (you'll notice I removed _all_ the cleanup from your example Dockerfile):

```dockerfile
FROM alpine AS sentry-build

ENV SENTRY_VERSION="1.19.1"

RUN apk add --no-cache \
		build-base \
		cargo \
		cmake \
		curl \
		curl-dev \
		file \
		gcc \
		openssl \
		openssl-dev \
		rust \
	&& cd /tmp \
	&& curl -LO https://github.com/getsentry/sentry-cli/archive/$SENTRY_VERSION.tar.gz \
	&& tar -xzf $SENTRY_VERSION.tar.gz \
	&& cargo build --manifest-path sentry-cli-$SENTRY_VERSION/Cargo.toml --release \
	&& mv sentry-cli-$SENTRY_VERSION/target/release/sentry-cli /usr/local/bin

FROM alpine

RUN apk add --no-cache curl llvm-libunwind openssl
COPY --from=sentry-build /usr/local/bin/sentry-cli /bin

CMD ["sh"]
```

```shell
$ docker image list
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sentry              test                d1d2388196ba        3 seconds ago       16.8MB
$ docker run -it sentry:test sentry-cli --version
sentry-cli 1.19.1
```

**Comment by mwarkentin** [comment]
I tried this out with the latest sentry CLI and got an error:

```
error: failed to run custom build command for `uchardet-sys v2.0.0`
process didn't exit successfully: `/tmp/sentry-cli-1.21.0/target/release/build/uchardet-sys-de96efdd507b27d4/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/uchardet-sys-2.0.0/uchardet" "-DBUILD_BINARY=OFF" "-DCMAKE_INSTALL_PREFIX=/tmp/sentry-cli-1.21.0/target/release/build/uchardet-sys-3100ef8028f6e95e/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -static" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -static" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
-- The CXX compiler identification is GNU 6.3.0
-- The C compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Skipping test da:iso-8859-1 (known broken)
-- Skipping test es:iso-8859-15 (known broken)
-- Skipping test he:iso-8859-8 (known broken)
-- Skipping test ja:utf-16be (known broken)
-- Skipping test ja:utf-16le (known broken)
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/sentry-cli-1.21.0/target/release/build/uchardet-sys-3100ef8028f6e95e/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--" "-j4"
Scanning dependencies of target libuchardet
Scanning dependencies of target libuchardet_static
[  0%] Building CXX object src/CMakeFiles/libuchardet.dir/CharDistribution.cpp.o
[  1%] Building CXX object src/CMakeFiles/libuchardet.dir/JpCntx.cpp.o
[  2%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangArabicModel.cpp.o
[  3%] Building CXX object src/CMakeFiles/libuchardet_static.dir/CharDistribution.cpp.o
[  4%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangBulgarianModel.cpp.o
[  4%] Building CXX object src/CMakeFiles/libuchardet_static.dir/JpCntx.cpp.o
[  5%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangCroatianModel.cpp.o
[  6%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangCzechModel.cpp.o
[  7%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangEsperantoModel.cpp.o
[  8%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangArabicModel.cpp.o
[  9%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangEstonianModel.cpp.o
[ 10%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangFinnishModel.cpp.o
[ 11%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangBulgarianModel.cpp.o
[ 12%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangFrenchModel.cpp.o
[ 13%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangCroatianModel.cpp.o
[ 14%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangCzechModel.cpp.o
[ 15%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangDanishModel.cpp.o
[ 16%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangEsperantoModel.cpp.o
[ 17%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangEstonianModel.cpp.o
[ 18%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangGermanModel.cpp.o
[ 19%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangFinnishModel.cpp.o
[ 20%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangFrenchModel.cpp.o
[ 21%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangGreekModel.cpp.o
[ 22%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangHungarianModel.cpp.o
[ 23%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangDanishModel.cpp.o
[ 24%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangHebrewModel.cpp.o
[ 25%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangIrishModel.cpp.o
[ 26%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangGermanModel.cpp.o
[ 27%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangGreekModel.cpp.o
[ 28%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangHungarianModel.cpp.o
[ 29%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangItalianModel.cpp.o
[ 30%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangLithuanianModel.cpp.o
[ 31%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangHebrewModel.cpp.o
[ 32%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangLatvianModel.cpp.o
[ 33%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangIrishModel.cpp.o
[ 34%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangPolishModel.cpp.o
[ 35%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangMalteseModel.cpp.o
[ 36%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangPortugueseModel.cpp.o
[ 37%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangRomanianModel.cpp.o
[ 38%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangRussianModel.cpp.o
[ 39%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangSlovakModel.cpp.o
[ 40%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangSloveneModel.cpp.o
[ 41%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangSwedishModel.cpp.o
[ 42%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangSpanishModel.cpp.o
[ 43%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangItalianModel.cpp.o
[ 44%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangLithuanianModel.cpp.o
[ 45%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangThaiModel.cpp.o
[ 46%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangTurkishModel.cpp.o
[ 47%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangLatvianModel.cpp.o
[ 48%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangMalteseModel.cpp.o
[ 49%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangPolishModel.cpp.o
[ 50%] Building CXX object src/CMakeFiles/libuchardet.dir/LangModels/LangVietnameseModel.cpp.o
[ 51%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangPortugueseModel.cpp.o
[ 52%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangRomanianModel.cpp.o
[ 53%] Building CXX object src/CMakeFiles/libuchardet.dir/nsHebrewProber.cpp.o
[ 54%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangSlovakModel.cpp.o
[ 55%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangRussianModel.cpp.o
[ 56%] Building CXX object src/CMakeFiles/libuchardet.dir/nsCharSetProber.cpp.o
[ 57%] Building CXX object src/CMakeFiles/libuchardet.dir/nsBig5Prober.cpp.o
[ 58%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangSwedishModel.cpp.o
[ 59%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangSloveneModel.cpp.o
[ 60%] Building CXX object src/CMakeFiles/libuchardet.dir/nsEUCJPProber.cpp.o
[ 61%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangSpanishModel.cpp.o
[ 62%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangThaiModel.cpp.o
[ 63%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangTurkishModel.cpp.o
[ 64%] Building CXX object src/CMakeFiles/libuchardet_static.dir/LangModels/LangVietnameseModel.cpp.o
[ 65%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsHebrewProber.cpp.o
[ 66%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsCharSetProber.cpp.o
[ 67%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsBig5Prober.cpp.o
[ 68%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsEUCJPProber.cpp.o
[ 69%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsEUCKRProber.cpp.o
[ 70%] Building CXX object src/CMakeFiles/libuchardet.dir/nsEUCKRProber.cpp.o
[ 71%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsEUCTWProber.cpp.o
[ 72%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsEscCharsetProber.cpp.o
[ 73%] Building CXX object src/CMakeFiles/libuchardet.dir/nsEUCTWProber.cpp.o
[ 74%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsEscSM.cpp.o
[ 75%] Building CXX object src/CMakeFiles/libuchardet.dir/nsEscCharsetProber.cpp.o
[ 76%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsGB2312Prober.cpp.o
[ 77%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsMBCSGroupProber.cpp.o
[ 78%] Building CXX object src/CMakeFiles/libuchardet.dir/nsEscSM.cpp.o
[ 79%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsMBCSSM.cpp.o
[ 80%] Building CXX object src/CMakeFiles/libuchardet.dir/nsGB2312Prober.cpp.o
[ 81%] Building CXX object src/CMakeFiles/libuchardet.dir/nsMBCSGroupProber.cpp.o
[ 82%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsSBCSGroupProber.cpp.o
[ 83%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsSBCharSetProber.cpp.o
[ 84%] Building CXX object src/CMakeFiles/libuchardet.dir/nsMBCSSM.cpp.o
[ 85%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsSJISProber.cpp.o
[ 86%] Building CXX object src/CMakeFiles/libuchardet.dir/nsSBCSGroupProber.cpp.o
[ 87%] Building CXX object src/CMakeFiles/libuchardet.dir/nsSBCharSetProber.cpp.o
[ 88%] Building CXX object src/CMakeFiles/libuchardet.dir/nsSJISProber.cpp.o
[ 89%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsUTF8Prober.cpp.o
[ 90%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsLatin1Prober.cpp.o
[ 91%] Building CXX object src/CMakeFiles/libuchardet_static.dir/nsUniversalDetector.cpp.o
[ 92%] Building CXX object src/CMakeFiles/libuchardet.dir/nsUTF8Prober.cpp.o
[ 93%] Building CXX object src/CMakeFiles/libuchardet_static.dir/uchardet.cpp.o
[ 94%] Building CXX object src/CMakeFiles/libuchardet.dir/nsLatin1Prober.cpp.o
[ 95%] Building CXX object src/CMakeFiles/libuchardet.dir/nsUniversalDetector.cpp.o
[ 96%] Linking CXX static library libuchardet.a
[ 97%] Building CXX object src/CMakeFiles/libuchardet.dir/uchardet.cpp.o
[ 97%] Built target libuchardet_static
[ 98%] Linking CXX shared library libuchardet.so
[ 98%] Built target libuchardet
Scanning dependencies of target uchardet-tests
[ 99%] Building C object test/CMakeFiles/uchardet-tests.dir/uchardet-tests.c.o
[100%] Linking C executable uchardet-tests

--- stderr
/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: attempted static link of dynamic object `../src/libuchardet.so.0.0.6'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/uchardet-tests.dir/build.make:96: test/uchardet-tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:198: test/CMakeFiles/uchardet-tests.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.26/src/lib.rs:599
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed
The command '/bin/sh -c apk add --no-cache 		build-base 		cargo 		cmake 		curl 		curl-dev 		file 		gcc 		openssl 		openssl-dev 		rust && cd /tmp 	&& curl -LO https://github.com/getsentry/sentry-cli/archive/$SENTRY_VERSION.tar.gz 	&& tar -xzf $SENTRY_VERSION.tar.gz 	&& cargo build --manifest-path sentry-cli-$SENTRY_VERSION/Cargo.toml --release 	&& mv sentry-cli-$SENTRY_VERSION/target/release/sentry-cli /usr/local/bin' returned a non-zero code: 101
make: *** [build] Error 101
```

Going back to 1.19.1 was able to build successfully I think:

```
warning: unused import: `libc::getpid`
 --> sentry-cli-1.19.1/src/utils/xcode.rs:8:5
  |
8 | use libc::getpid;
  |     ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: field is never used: `config`
   --> sentry-cli-1.19.1/src/utils/xcode.rs:286:5
    |
286 |     config: &'a Config,
    |     ^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

    Finished release [optimized] target(s) in 421.79 secs
```

**Comment by oscar-b** [comment]
@mwarkentin I also had problems with newer versions of sentry-cli when I tested a while ago, and I think it was caused by an old version of Rust provided by the Alpine package.

@jan-auer I will try to get this updated when I find some free time, last time I tried I ran into the issue with not being able to compile the latest version.

**Comment by jan-auer** [comment]
All builds as of version `1.20.0` will fail due to the [uchardet](https://github.com/emk/rust-uchardet) dependency. Once emk/rust-uchardet#9 is merged, this should build fine on `alpine:edge`. 

Note that we require a more recent rust compiler than 1.17, which is included in `alpine:latest`. Building in `latest` would require to compile cargo and rustc from scratch (that is, I'm not aware of any other way).

Here is an example Dockerfile that will build (once the above fix is applied) and also defaults to the latest sentry-cli version if no `--build-arg SENTRY_VERSION=` is given:  

```dockerfile
FROM alpine:edge AS sentry-build

RUN apk add --no-cache \
    cargo \
    cmake \
    curl \
    curl-dev \
    g++ \
    jq \
    make \
    openssl \
    openssl-dev \
    rust

ARG SENTRY_VERSION
WORKDIR /tmp

RUN SENTRY_VERSION=${SENTRY_VERSION:-$(curl https://api.github.com/repos/getsentry/sentry-cli/releases/latest | jq -r '.tag_name')} \
    && curl -LO https://github.com/getsentry/sentry-cli/archive/$SENTRY_VERSION.tar.gz \
    && tar -xzf $SENTRY_VERSION.tar.gz \
    && cargo build --manifest-path sentry-cli-$SENTRY_VERSION/Cargo.toml --release \
    && mv sentry-cli-$SENTRY_VERSION/target/release/sentry-cli /usr/local/bin

FROM alpine

RUN apk add --no-cache curl llvm-libunwind openssl
COPY --from=sentry-build /usr/local/bin/sentry-cli /bin

CMD ["sh"]
```

**Comment by mitsuhiko** [comment]
Is there a specific reason one wants this in a docker container? Wouldn't it be more useful if we just distribute a binary that can run on alpine?

**Comment by mwarkentin** [comment]
That’d be just fine for us.

**Comment by jan-auer** [comment]
We've fixed issues with building sentry-cli on Alpine and added a Dockerfile as well as updated the readme in https://github.com/getsentry/sentry-cli/commit/6f3f14497cc37637935042971af896d79cc415f9. Starting with the next release, just check out the latest source tarball on the [releases](https://github.com/getsentry/sentry-cli/releases) page and build with the provided instructions. 

Thank you for providing feedback, mentioning the staged docker build process and the time invested in tracking missing dependencies. In near future, we'll start publishing Docker images on Dockerhub as part of our release process, so you don't have to build yourself anymore. 

In case you run into issues with the current Dockerfile or have suggestions, please feel free to file an issue or open a new PR.

**Pull request closed without merging**
