### PR TITLE
fix: add support for react-native >= 0.46.X

### PR DESCRIPTION
**Pull request by stephan-nordnes-eriksen**
This adds support for newer react-native versions.

Ref: https://github.com/facebook/react-native/issues/14935

### CODE REVIEW

**Comment by mitsuhiko** [comment]
@HazAT can you fix up the patch to support old and new?

**Comment by HazAT** [comment]
@mitsuhiko `0.46` is over a year old, not sure if it's worth it to patch this. 
Also, the latest release of our react-native SDK only supports RN >= 0.56.

**Comment by HazAT** [comment]
So we can merge it the way it is imho

**Comment by HazAT** [comment]
Let's merge this!

**Pull request merged**
