### PR TITLE
Move progress bar code into submodule

### PR DESCRIPTION
**Pull request by szokeasaurusrex**
Moving the progress bar code into a submodule will allow us to move the `ProgressBarMode` code from the `api` module next to the progress bar code. I will create a separate PR to move the `ProgressBarMode` code

### CODE REVIEW

**Comment by loewenheim** [comment]
I'm not sure why moving `ProgressBarMode` here requires the creation of a `bar` module? Without the further change, this just leaves the `progress` module empty. Is there a reason all the progress bar code can't be in one file?

**Comment by szokeasaurusrex** [comment]
@loewenheim I made those changes in #2042, which depends on this PR, and which it seems you already approved. I had forgotten to request review on this PR at the same time, sorry if that caused any confusion!

**Comment by loewenheim** [comment]
(I assume you mean #2041)

Right. Looking at both these PRs together, I think the `progress` module is small enough (around 100 lines) that splitting it into `bar` and `mode` modules is unnecessary, but it's up to you.

**Comment by szokeasaurusrex** [comment]
> Right. Looking at both these PRs together, I think the progress module is small enough (around 100 lines) that splitting it into bar and mode modules is unnecessary, but it's up to you.

Okay, then I will have everything in a single module. I changed #2041 accordingly, and will close this PR in favor of #2041

**Pull request closed without merging**
