### PR TITLE
chore(backport): Replace `npmlog` dependency in order to avoid vulnerability

### PR DESCRIPTION
**Pull request by mydea**
This is a backport of https://github.com/getsentry/sentry-cli/pull/1392, as we sadly still got some issues to figure out before we can update the webpack plugin to use v2 of sentry-cli.

We keep getting (every now and then) bumped on this security vulnerability, so we'd like to get this off our plate by backporting this fix and releasing it as 1.x.

### CODE REVIEW

**Comment by mydea** [comment]
Not really sure if the test failures are due to this PR...?

**Review by Lms24 — APPROVED** [review]
Thanks!

**Comment by kamilogorek** [comment]
fixed it for you.

**Comment by mydea** [comment]
> fixed it for you.

Ah, thanks a lot! 🎉

**Review by AbhiPrasad — APPROVED** [review]
:shipit:

**Comment by mydea** [comment]
So I'll merge this in @kamilogorek, can you cut a release on the 1.x branch?

**Pull request merged**
