### PR TITLE
ref: Update to 1.30 idioms

### PR DESCRIPTION
**Pull request by mitsuhiko**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Yeah. Wanted to change away from old macro import but there is so much stuff that needs to be changed but sadly rustfix can’t do those yet.

**Comment by jan-auer** [comment]
Alright, those macro imports are really bad, let's wait for an autofix.

**Comment by mitsuhiko** [comment]
blaze it?

**Comment by jan-auer** [comment]
go :shipit:

**Pull request merged**
