### PR TITLE
ref(inject): Print list of processed files

### PR DESCRIPTION
**Pull request by loewenheim**
This prints the list of files processed by `sourcemaps inject` in the following format:

For example:
```
Injected source files:
  - 35cd5385-93b1-4a0c-9b8c-97200ed2479c - inject_test/nextjs-build-output/server/app/client/page.js
  - 1f037a16-e9a0-4e4d-8365-5ff23e93e573 - inject_test/nextjs-build-output/server/app/error/page.js
  - 4fbee445-a522-4fbb-8131-07915f09aba6 - inject_test/nextjs-build-output/server/app/page.js
  - 797e7c95-9160-4a98-92ee-847edd53ff99 - inject_test/nextjs-build-output/server/chunks/1.js
  - 2ecf9936-a38b-45d5-85ae-3d555b26f556 - inject_test/nextjs-build-output/server/chunks/107.js

Skipped: files without sourcemap references:
  - inject_test/nextjs-build-output/server/chunks/flight-server-css-manifest.js
  - inject_test/nextjs-build-output/server/flight-manifest.js
  - inject_test/nextjs-build-output/server/flight-server-css-manifest.js
  - inject_test/nextjs-build-output/server/font-loader-manifest.js
  - inject_test/nextjs-build-output/server/middleware-build-manifest.js

Injected sourcemap files:
  - 35cd5385-93b1-4a0c-9b8c-97200ed2479c - inject_test/nextjs-build-output/server/app/client/page.js.map
  - 1f037a16-e9a0-4e4d-8365-5ff23e93e573 - inject_test/nextjs-build-output/server/app/error/page.js.map
  - 4fbee445-a522-4fbb-8131-07915f09aba6 - inject_test/nextjs-build-output/server/app/page.js.map
  - 797e7c95-9160-4a98-92ee-847edd53ff99 - inject_test/nextjs-build-output/server/chunks/1.js.map
```

The format is still up for debate. Also, the code might be a bit messy.

### CODE REVIEW

**Comment by Jesse-Box** [comment]
cc: @mitsuhiko 

Here's the copy I think we should have for each section

`Modified: The following files have been modified to have debug ids`

`Ignored: The following files already have debug ids`

`Ignored: The following files don't have sourcemap references `

**Review by mitsuhiko — CHANGES_REQUESTED** [review]
Can you change the headings to the ones from @Jesse-Box and then we can push this out.

**Comment by kamilogorek** [comment]
Could we maybe have an integration test that'll verify those reports are generated correctly?

**Review by Jesse-Box — APPROVED** [review]

**Comment by loewenheim** [comment]
> Could we maybe have an integration test that'll verify those reports are generated correctly?

Do you mean like a snapshot test with some example project?

**Comment by kamilogorek** [comment]
> Do you mean like a snapshot test with some example project?

Basically yes.

- have a prepared fixture
- when test runs
  - create temp dir
  - copy fixtures over
  - run inject over them
  - command output snapshot

**Comment by kamilogorek** [comment]
- added integration test for all possible outcomes
- changed formatting and ordering
- removed most fixtures (there were way too many of them)
- changed `warn!` to `debug!` when file is not found, as report will already tell that

Note: sourcemap with already existing debug_id won't be reported if the only source pointing to this map also already have a debug_id, as it will early-exit. This is a scenario that should almost never happen, but I modified the fixtures to still trigger this report case.

**Pull request merged**
