### PR TITLE
feat: Use secured base Docker image for Linux builds

### PR DESCRIPTION
**Pull request by tonyo**
Also: 
* Change entrypoint for resulting Dockerfile
* Add smoke tests for built binaries

### CODE REVIEW

**Comment by tonyo** [comment]
Ready for review.

**Comment by mitsuhiko** [comment]
We could also make it send an HTTP request with a known token.

**Comment by tonyo** [comment]
@mitsuhiko Added an invocation of `releases list` as a basic check.

**Comment by mitsuhiko** [comment]
Sehksi!

**Pull request merged**
