### PR TITLE
feat: Add better error reporting for config related io errors

### LINKED ISSUE #144: Give better context to IO errors
Currently IO errors (such as the one in #142) are not well reported to the user. We never annotate the filename we attempt to reference. We should properly contextualize all IO access so users are less likely to be presented with useless error messages.

### PR DESCRIPTION
**Pull request by mitsuhiko**
Refs #142
Fixes #144

### CODE REVIEW

**Comment by chrusart** [comment]
It contains 'secrets', I'm not sure about that, console output can be redirected somewhere where you don't wanna have such data, just my opinion.

**Comment by mitsuhiko** [comment]
@chrusart why does it contain secrets?

**Comment by chrusart** [comment]
```auth.token``` ?

**Comment by mitsuhiko** [comment]
@chrusart but not in the file name.

**Comment by chrusart** [comment]
Ohh, yes, I'm still in the context of circleci where I had conte there as base64, sorry.

**Comment by marcomorain** [comment]
🎉 nice one.

**Pull request merged**
