### PR TITLE
`brew install` works

### PR DESCRIPTION
**Pull request by mxcl**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
@mxcl so i added the install instructions for this:

```
brew install getsentry/tools/sentry-cli
```

We're not maintaining a public sentry-cli formula so pretty sure the install command you PRed should not work?

**Comment by mxcl** [comment]
My bad, thanks for the correction.

**Comment by mitsuhiko** [comment]
I wanted to add it to brew directly but it's no fun to compile it from source :)

**Comment by mxcl** [comment]
Hah, tell me about (generally) it…

**Pull request closed without merging**
