### PR TITLE
Bump mach_object to fix compile issue on ARM

### PR DESCRIPTION
**Pull request by kirkins**
https://github.com/flier/rust-macho/issues/11

### CODE REVIEW

**Comment by kirkins** [comment]
I guess I need to update the lock file.

I assumed this would just work, but owner of the library also bumped a few other libraries when they applied the change I needed.

Now when I'm running `cargo build` I get back:

```
   Compiling parking_lot_core v0.2.6
error: `pub(restricted)` syntax is experimental (see issue #32409)
    --> /home/philip/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.6/src/parking_lot.rs:1086:9
     |
1086 |     pub(super) struct DeadlockData {}
     |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
    --> /home/philip/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.6/src/parking_lot.rs:1090:13
     |
1090 |         pub(super) fn new() -> Self {
     |             ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
    --> /home/philip/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.6/src/parking_lot.rs:1122:9
     |
1122 |     pub(super) unsafe fn on_unpark(_td: &super::ThreadData) {
     |         ^^^^^

error: aborting due to 3 previous errors

   Compiling phf_generator v0.7.21
error: Could not compile `parking_lot_core`.
Build failed, waiting for other jobs to finish...
error: build failed
```
I'm not sure what went wrong. These are the dependencies that changed https://github.com/flier/rust-macho/commit/561a52e40da59a5b4b0992efd620053436a5862d

**Comment by kirkins** [comment]
To clarify I'm compiling on desktop (not ARM) when I get the failure from the new dependencies.

**Comment by kirkins** [comment]
Doh, realizing this morning that the computer I was using had a really old of Rust. That's probably why it failed. Going to try to compile again now.

**Comment by kirkins** [comment]
Had to update a second library related to the same issue. After that I was able to completely compile on ARM7.

Author of `uchardet` [was saying ](https://github.com/emk/rust-uchardet/issues/13)you should switch to `chardet` because:

> The big win here is that you'll no longer require cmake or a C++ compiler to build this part of your program. And you'll be able to cross-compiler with musl-libc, producing entirely static binaries.

`uchardet` is only used once in the project. I tried changing it myself but I'm still having [trouble converting](https://github.com/kirkins/sentry-cli/commit/7c826ca70fef22b2e50dbd95fd47a1f27b94a509#diff-ac7a24020908152dd824a59b923f0247R17) to the right type.

**Comment by kirkins** [comment]
Rolling back the upgrade on uchardet to avoid conflict with https://github.com/getsentry/sentry-cli/pull/185

**Comment by jan-auer** [comment]
Hi, we just ran a complete dependency update on all, which includes `mach_object`. Thanks anyway :)

**Pull request closed without merging**
