### PR TITLE
feat: Add url-suffix option

### PR DESCRIPTION
**Pull request by kamilogorek**
To support query params, eg. https://github.com/getsentry/sentry-webpack-plugin/issues/65

### CODE REVIEW

**Comment by mitsuhiko** [comment]
@jan-auer fwiw this commit broke sentry-cli's sourcemap command:

```
```thread 'unnamed' panicked at 'Argument short must be unique

    -u is already in use': /Users/mattenoble/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.32.0/src/app/parser.rs:186```
```

**Comment by kamilogorek** [comment]
Aww snap. Same `short` :S

**Comment by Polm90** [comment]
is this option released in the current sentry-cli? I don't find it in the documentation...
Thank you!

**Comment by kamilogorek** [comment]
It is:

image

image

**Pull request merged**
