### PR TITLE
feat: add skip confirmation arg to uninstall cmd

### PR DESCRIPTION
**Pull request by erictaylor**
This adds a `--skip-confirmation` argument to the `uninstall` command.

I use this tool on CI/Docker and uninstall after use so it doesn't add to an image. Uninstalling with the confirmation prompt is an issue, so having an argument like this ideal to skip the confirmation prompt all together and simply uninstall.

---

This is my first Rust code ever written, so please be gentle if I made a mistake. 😆

### CODE REVIEW

**Comment by kamilogorek** [comment]
The code looks good, thanks! :) Can we rename the flag to `--confirm` instead? This is what some of the CLI tools that I know already use.

**Comment by kamilogorek** [comment]
You can use `make lint` and `make format` to fix linting issues. And once you rebase on top of master, build failure should be gone as well.

**Comment by erictaylor** [comment]
@kamilogorek I've updated the option to `confirm` and rebased from `master` as requested. When I run `make lint` I get two errors that don't appear to be related to my changes. Let me know if there is anything else I need to correct/change. 😄

**Comment by kamilogorek** [comment]
Looks good and passes all checks. Thanks! :)

**Comment by erictaylor** [comment]
@kamilogorek just curious when I might see a release including this?

**Comment by kamilogorek** [comment]
@erictaylor I'll cut the new release Today in few hours

**Comment by kamilogorek** [comment]
Released as `1.56.0`. Cheers!

**Pull request merged**
